LOCAL_PATH:= $(my-dir)

include $(CLEAR_VARS)
LOCAL_PREBUILT_EXECUTABLES := isu
LOCAL_REQUIRED_MODULES := isu_stream
include $(BUILD_HOST_PREBUILT)

include $(CLEAR_VARS)
LOCAL_PREBUILT_EXECUTABLES := isu_stream
include $(BUILD_HOST_PREBUILT)

include $(CLEAR_VARS)
LOCAL_PREBUILT_EXECUTABLES := isu_wrapper.sh
LOCAL_REQUIRED_MODULES := isu
include $(BUILD_HOST_PREBUILT)
